### ISSUE TITLE
Incompatibility with the "Babel ES6/ES7" VSCode plugin

### ISSUE THREAD

**Issue by Alexintosh** [styled-components/vscode-styled-components#23] opened 2017-05-16 11:08 UTC
I'm not sure why but I'm not getting any syntax highlighting.

**Comment by GoldenRust** [comment] 2017-05-17 12:28
+1 Same issue here

**Comment by svipben** [comment] 2017-05-21 21:52
@julienp any news on this?

**Comment by julienp** [comment] 2017-05-22 07:48
It's working for me in the latest VSCode. Could it be a conflicting plugin? See https://github.com/styled-components/vscode-styled-components/issues/8

**Comment by svipben** [comment] 2017-05-22 08:09
@julienp Yes, for me too. Didn't tested before comment, sorry...

**Comment by tijs** [comment] 2017-07-25 08:06
I have the same issue but get the colouring back when disabling the Babel es6/es7 extension (dzannotti.vscode-babel-coloring). Would be nice to have them both to be honest as both are a solid improvement to vscode.

**Comment by Alexintosh** [comment] 2017-07-27 07:05
@svipben my extensions:
```
Angular.ng-template
EQuimper.react-native-react-redux
PKief.material-icon-theme
RobinMalfait.prettier-eslint-vscode
Thavarajan.ionic2
UVBrain.Angular2
WallabyJs.wallaby-vscode
Zignd.html-css-class-completion
abusaidm.html-snippets
alefragnani.project-manager
buzatto.ionic-extension-pack
christian-kohler.path-intellisense
danielehrhardt.ionic3-vs-ionView-snippets
dbaeumer.vscode-eslint
dzannotti.vscode-babel-coloring
eg2.tslint
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
jgw9617.ionic2-vscode
johnpapa.Angular2
jpoissonnier.vscode-styled-components
mrmlnc.vscode-scss
oderwat.indent-rainbow
pkosta2006.rxjs-snippets
robertohuertasm.vscode-icons
```
steoates.autoimport
vscodevim.vim
vsmobile.cordova-tools
wcwhitehead.bootstrap-3-snippets
xabikos.JavaScriptSnippets

**Comment by eric-burel** [comment] 2017-08-04 14:44
Same issue, there is an incompatibility with Babel ES6/ES7

**Comment by Alexintosh** [comment] 2017-08-17 09:16
@eric-burel thanks for the tip!
Is there any plan to fix this?

**Comment by Cu3PO42** [comment] 2018-04-12 13:32
I can confirm that this is still an issue with that particular plugin.

vscode-styled-components works by injecting additional rules into the JavaScript (and TypeScript) grammar which can be quite finicky and relies on some details of that grammar to work correctly. Since "Babel ES6/ES7" changes the grammar quite significantly these incompatibilities are easily explained.

"Babel ES6/ES7" is not actively maintained and hasn't received an update for almost two years and I fail to see the advantages over the grammar shipping with VSCode.

Personally I think compatibility with all custom grammars is not a realistic goal to achieve, therefore this would fall in the category of "won't fix". How do you see this @julienp?

**Comment by infodevart** [comment] 2018-06-20 10:46
same problem here ... it work well only if i disable "Babel javascript" package

**Comment by saurabhkanswal** [comment] 2018-11-30 17:45
make sure your theme should be the default
file->prefrences->themecolor->choose default theme 
.hope this will work

**Comment by jasonwilliams** [comment] 2020-10-05 11:24
Closing due to inactivity

**Closed by jasonwilliams** 2020-10-05 11:24 UTC
Labels: bug, injection-grammar
