### ISSUE TITLE
Syntax highlighting breaks if there is a linebreak between "styled" and opening backtick `

### ISSUE THREAD

**Issue by Livven** [styled-components/vscode-styled-components#174] opened 2019-05-29 10:58 UTC
See the screenshot, once there is a linebreak between `styled` and the opening backtick `` ` `` CSS syntax highlighting stops working. A normal use case for this would be e.g. declaring an anonymous interface for `props` in Typescript that spans multiple lines.

![Screenshot](https://user-images.githubusercontent.com/1537947/58551358-154d8400-8210-11e9-9bea-f905980b1f3a.png)

**Comment by tywmick** [comment] 2021-02-18 00:07
I tried replacing every `<.+>` in [the regex](https://github.com/styled-components/vscode-styled-components/blob/0fb3ec7027ac6e0541fad7d68176f25b3d357169/syntaxes/styled-components.json#L7) with `<.*?(?:\\n.*?)*?>` and later with `<[^>]*?>` to try to allow new line characters, but neither of those fixed the issue for me, either. 😔

**Comment by rkingon** [comment] 2021-04-21 16:38
i'm trying to convert to styled components and this is killlllllling me =x

**Comment by jasonwilliams** [comment] 2021-04-21 18:48
The issue is this https://github.com/styled-components/vscode-styled-components/blob/master/CONTRIBUTING.md#a-line-break-seems-to-break-the-syntax-highlighting so we know what is causing it now it’s just a case of fixing it.

**Comment by jasonwilliams** [comment] 2021-04-24 00:07
This has been fixed in [v1.5.1](https://github.com/styled-components/vscode-styled-components/releases/tag/v1.5.1) please let us know or raise an issue if this is still happening

**Closed by jasonwilliams** 2021-04-24 00:07 UTC
Labels: TypeScript, bug

**Comment by rkingon** [comment] 2021-05-07 18:36
It looks like there is still a scenario in which the syntax stops working (though I have found it to be greatly improved from other areas (like defining types or attributes).

<img width="1192" alt="Screen Shot 2021-05-07 at 11 35 11 AM" src="https://user-images.githubusercontent.com/3946301/117493949-83d10b80-af28-11eb-9be3-194c66898033.png">

**Comment by rkingon** [comment] 2021-05-07 18:40
Just for fun, here are two other screenshots, where if I pull the FC out into a variable and keep the styled call on a single line, it works -- but if I make it multi line, it stops.

<img width="1180" alt="Screen Shot 2021-05-07 at 11 39 13 AM" src="https://user-images.githubusercontent.com/3946301/117494233-e62a0c00-af28-11eb-92d4-56ec2b962d9f.png">

<img width="1192" alt="Screen Shot 2021-05-07 at 11 39 25 AM" src="https://user-images.githubusercontent.com/3946301/117494236-e75b3900-af28-11eb-9e50-cc288da8812b.png">

**Comment by jasonwilliams** [comment] 2021-05-07 20:24
Hey @rkingon, thanks for finding that.
Are you able to make a new issue for that?
