### ISSUE TITLE
Incorrect cursor placement after autocomplete

### ISSUE THREAD

**Issue by mateuszral** [styled-components/vscode-styled-components#376] opened 2022-08-27 14:41 UTC
Describe the bug (including copyable syntax)
CSS autocomplete cursor position af
The cursor is right before the last character of the last word.

Screenshot

displa/*the cursor is currently here*/y: ;
![image](https://user-images.githubusercontent.com/77389967/187034967-5f2399f1-1f32-4a78-ba2b-495fec16bfa8.png)

To Reproduce
Add any css property, then hit enter on any suggestions.

![image](https://user-images.githubusercontent.com/77389967/187035081-e5afd8e0-c2de-49a3-8bcf-0d9c9c9b8ad2.png)

Expected behavior
The cursor should be BETWEEN the colon and the semi colon

display: /*the cursor should be here*/ ;

![image](https://user-images.githubusercontent.com/77389967/187035012-b4519563-fd3c-4811-93cd-d5acdf0b31e2.png)

Build environment:

OS: Windows 11 21H2 
OS Build: 22000.856
VSCode Version: 1.71
Extension Version 1.7.4

**Comment by Sirs0ri** [comment] 2022-09-07 15:16
Duplicate of #370, which has a potential fix

**Comment by mateuszral** [comment] 2022-09-23 20:17
> Duplicate of #370, which has a potential fix

Reinstalling didn't work for me. Still having this bug.

**Comment by oscarvz** [comment] 2022-09-29 09:32
I had the same issue @mateuszral, just reinstalling didn't work. What _did_ work for me though, was:
- Uninstalling extension & reload VS Code
- `ctrl / cmd` + `shift` + `p` => type 'clear' => select `Clear Editor History`
- `ctrl / cmd` + `shift` + `p` => type 'clear' => select `Search: Clear Search History`
- Reinstall the extension

See if this works for you too! I can confirm this works on macOS.

**Comment by carlos3duardo** [comment] 2022-10-15 18:57
I have the same problem with Linux Zorin OS 16. =(
Reinstall the extention didn't work for me.

**Comment by carlos3duardo** [comment] 2022-10-15 19:06
This!! https://github.com/styled-components/vscode-styled-components/issues/366#issuecomment-1086782239

**Closed** 2022-10-15 19:07 UTC
Labels: bug
