### ISSUE TITLE
Autocomplete on pseudo-classes (eg. `:not`) or pseudo-elements results in too many colons

### ISSUE THREAD

**Issue by karlhorky** [styled-components/vscode-styled-components#336] opened 2021-11-17 15:07 UTC
**Describe the bug (including copyable syntax)**

1. When selecting any pseudo-classe from the VS Code autocomplete, two colons are entered incorrectly (pseudo-classes use a single colon)
2. When selecting any pseudo-element from the VS Code autocomplete, three colons are entered incorrectly (pseudo-elements use two colons)

Eg. entering either `:not` or `::before` and selecting the autocomplete item in VS Code results in incorrect code:

```js
const createNewCompanyStyles = css`
  display: flex;

  > div {
    margin-bottom: 32px;
  }
`;
```

**Video**

https://user-images.githubusercontent.com/1935696/142225245-07f5c9b4-c67f-42a7-9bb1-1aab32bd29fe.mp4

**To Reproduce**

Reproduction steps above

**Expected behavior**

Autocomplete entries should not result in incorrect CSS code

**Build environment (please complete the following information):**

- OS: macOS Monterey 12.0.1
- VSCode Version: 1.62.1
- Extension Version 1.6.6

**Comment by karlhorky** [comment] 2021-11-17 15:14
Even worse, there's actually no way to escape from this bug (unless you do something tricky like copy/pasting code), because just continuing with the `(` after the `:not` causes the autocomplete item to be selected 😫

https://user-images.githubusercontent.com/1935696/142227266-9f41513c-0037-4c1d-a590-db7592739db6.mp4

**Comment by jasonwilliams** [comment] 2021-11-17 15:41
This is a duplicate of https://github.com/styled-components/vscode-styled-components/issues/325 please add to that conversation for this

**Closed by jasonwilliams** 2021-11-17 15:41 UTC
Labels: bug

**Comment by jasonwilliams** [comment] 2021-11-17 15:50
@karlhorky  we are also looking for help to fix this issue, so please feel free to join on that issue if you have any spare time

**Comment by karlhorky** [comment] 2021-11-17 15:58
@jasonwilliams Ah sorry for the duplicate! I tried searching but didn't find any of the keywords I used (but now it will be easier to find it for others)

I'll post my content over there too 👍

**Comment by karlhorky** [comment] 2021-11-17 16:03
@jasonwilliams same situation as with my other issue - happy to jump in and do a quick 1-2 file edit if I can read where the bug is (or if you can guide me to it), but I won't have time currently to get familiar with a new codebase and set up the project on my system. Just finishing up two cohorts of [upleveled.io](https://upleveled.io) students and launching a new product, currently have no extra time. Maybe early next year.
