### ISSUE TITLE
Keyframes with percentages causes error highlighting

### ISSUE THREAD

**Issue by claygiffin** [styled-components/vscode-styled-components#293] opened 2021-05-19 18:24 UTC
**Description**

When using styled keyframes, syntax highlighting breaks if using percentages instead of 'from' and 'to'. 

Error message: `{ expectedts-styled-plugin(9999)`

**Screenshot**
![image](https://user-images.githubusercontent.com/31489375/118863766-275cdd00-b894-11eb-8041-e9257e810852.png)

**Build environment:**
- OS: MacOS 11.3
- VSCode Version: 1.56.2
- Extension Version: 1.6.1

**Additional context**
Problem is resolved by rolling back to previous version

**Comment by justintemps** [comment] 2021-05-20 15:25
Also having this issue.

**Comment by ruvkr** [comment] 2021-05-21 10:10
Having this issue

**Comment by rafaelpizzo** [comment] 2021-05-21 10:10
Started having this issue since upgrading to 1.6.1 onwards

**Comment by jasonwilliams** [comment] 2021-05-21 10:55
Would appreciate help on this one, now that ts styled plugin is parsing the css it’s probably not aware it’s a styled block. So confused by the percentages. If there’s some way to tell the css language service that this is a keyframes block that would be good. Contributing guide shows how to debug this.

@mjbvz do you know if this is fixable?

**Comment by wdcarlos** [comment] 2021-05-21 13:13
Same here :/ Only way to not have this problem is with {from: ... to: ....} syntax. Downgrading to 1.5.2 here until this get fixed.

**Comment by jasonwilliams** [comment] 2021-05-21 16:45
So the main issue here is that TypeScript Styled Plugin wraps all css in `:root` here https://github.com/microsoft/typescript-styled-plugin/blob/main/src/_virtual-document-provider.ts#L24

We would need some way to dynamically change that to `@keyframes` when the keyframes tag is used

**Comment by jasonwilliams** [comment] 2021-05-21 16:50
Upstream issue: https://github.com/microsoft/typescript-styled-plugin/issues/137

**Comment by marcosem** [comment] 2021-05-23 17:04
Have same issue.

**Comment by eomttt** [comment] 2021-05-24 05:34
Have same issue

**Comment by jasonwilliams** [comment] 2021-05-24 09:14
@marcosem @eomttt please don't reply saying you "have the same issue", there are people subscribed to this thread and it pings everyone. 

If you want to signal you have this issue please upvote the top post with a "thumbs up" emoji. Same goes for anyone else.

**Comment by jasonwilliams** [comment] 2021-05-26 16:41
I've opened a PR [upstream](https://github.com/microsoft/typescript-styled-plugin/issues/137) so it will just depend how long they will need to merge it. Nothing left for me to do on this side.

**Comment by anteronunes** [comment] 2021-05-28 13:19
Hi, guys. This workaround works fine for me, if you want to give it a try...

![animation_workaround](https://user-images.githubusercontent.com/31047670/119989800-f8ceb880-bf9d-11eb-8b08-766fffb6c84e.PNG)

**Comment by jasonwilliams** [comment] 2021-06-01 20:35
First of all apologies for the regression.

As this still hasn't been merged upstream I have [put out a release](https://github.com/styled-components/vscode-styled-components/releases/tag/v.1.6.4) which includes a roll-back of TypeScript Styled Plugin to v0.16, which is before it started parsing the `keyframes` tag. This should (in theory) remove the errors you've been getting, however you also won't get any intellisense in `keyframes` blocks.

For those of you who are after `keyframes` intellisense you can subscribe to that issue here:
https://github.com/styled-components/vscode-styled-components/issues/301

For everyone else its just a case of updating and letting us know if you spot any problems

**Closed by jasonwilliams** 2021-06-01 20:35 UTC
Labels: bug, upstream

**Comment by stephenhuh** [comment] 2022-08-17 18:06
regression seen in v1.7.4

doesn't seem to be an issue in v1.7.0

use the following snippet:
```
const animation = props => css`
  ${pulse} 2s infinite;
`

const pulse = keyframes`
  0% {
    transform: scale(0.95);
    box-shadow: 0 0 0 0 rgba(224, 231, 255, 0.7);
  }
  
  70% {
    transform: scale(1);
    box-shadow: 0 0 0 10px rgba(224, 231, 255, 0);
  }
  
  100% {
    transform: scale(0.95);
    box-shadow: 0 0 0 0 rgba(224, 231, 255, 0);
  }
}
`

```
