### ISSUE TITLE
Intellisense not working, March 2023

### ISSUE THREAD

**Issue by sunflowerm** [styled-components/vscode-styled-components#404] opened 2023-03-18 09:02 UTC
**The bug**
I am not able to get any styled-components autocomplete suggestions within my typescript JSX files. It used to work. I have updated VS Code Insiders on Windows 10 to the latest version, vs-code styled-components to 1.7.5 (Pre-release), all packages with yarn. 

I have looked at  #343 , and hence updated everything, but to no avail.
I have also looked at #387 , but I dont have Nightly installed.

**Screenshot**   
![image](https://user-images.githubusercontent.com/98698774/226095616-c2e9201c-364a-4dde-b587-50fd23dde60b.png)

**Expected behavior**   
Give autosuggestions. 
e.g. aic > align-items:center;
jcc > justify-content:center;

**Build environment (please complete the following information):**

- OS: [Windows 10]
- VSCode Version: [Version 1.77.0-insider]
- Extension Version [1.7.5 (Pre-release)]

**Additional context**   
I have tried to provide all information that I could think of which was relevant, let me know if there's anything else!

**Comment by jasonwilliams** [comment] 2023-04-01 17:55
This is a duplicate of https://github.com/styled-components/vscode-styled-components/issues/387

**Closed by jasonwilliams** 2023-04-01 17:55 UTC
Labels: bug

**Comment by karelric** [comment] 2023-04-03 03:20
Same happening to me without any luck. I tried everything I read and know. PS I am using TS 4.x
