### ISSUE TITLE
shadow- and elevation Selectors Not Recognized

### ISSUE THREAD

**Issue by richpriordesign** [styled-components/vscode-styled-components#210] opened 2020-02-11 17:40 UTC
In VSCode when adding shadow-color, shadow-opacity, shadow-offset, shadow-radius and elevation it is marked as incorrect code by VSCode with the vscode-styled-components plugin. These are used to replicate box-shadow on iOS and Android in React Native.

<img width="349" alt="shadow elevation errors" src="https://user-images.githubusercontent.com/14063124/74262832-a5aef480-4ccb-11ea-9783-bc3a2ddcba60.png">

**Comment by alexvilchis** [comment] 2020-09-10 20:41
I have this issue too; it's annoying :disappointed:

**Comment by jasonwilliams** [comment] 2020-10-08 18:22
Dupe of https://github.com/styled-components/vscode-styled-components/issues/91

**Closed by jasonwilliams** 2020-10-08 18:22 UTC
