### ISSUE TITLE
Add colon on css property completion?

### ISSUE THREAD

**Issue by vhflat** [styled-components/vscode-styled-components#172] opened 2019-05-15 10:15 UTC
When completing a css property with intellisense it doesn't add a colon.

Is this a bug or a feature?

**Comment by simpleshadow** [comment] 2019-06-10 21:32
Ya, wish this was here too… Also, I'm not getting value suggestions.

**Comment by Bat1sta** [comment] 2019-12-21 14:59
This really is a complicated problem, it sounds silly, but it makes development much more laborious.

**Comment by theonlydaleking** [comment] 2020-02-02 01:03
Do we know if this ever will be implemented or no?

**Comment by dilincoln** [comment] 2020-04-12 20:47
Any solution?

**Comment by dilincoln** [comment] 2020-04-13 11:13
> This really is a complicated problem, it sounds silly, but it makes development much more laborious.

take a look

https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components

**Comment by jasonwilliams** [comment] 2020-10-08 18:06
@dilincoln is this something you'd be happy PRing here?

**Comment by dilincoln** [comment] 2020-10-08 23:42
Hey @jasonwilliams ! I'm testing this version forked by me to ensure that works perfectly but i pretend to make a PR soon =)

**Comment by jasonwilliams** [comment] 2020-10-09 08:57
closing as a dupe of https://github.com/styled-components/vscode-styled-components/issues/220 continuing there

**Closed by jasonwilliams** 2020-10-09 08:57 UTC
Labels: Hacktoberfest, enhancement

**Comment by jasonwilliams** [comment] 2021-05-04 10:27
> > This really is a complicated problem, it sounds silly, but it makes development much more laborious.
> 
> take a look
> 
> https://marketplace.visualstudio.com/items?itemName=diegolincoln.vscode-styled-components

Thanks for making that fork @dilincoln 

That code is now upstream in this repo, the only difference is instead of a hardcoded list of CSS properties we utilies the css language service. Will be released in v1.6.0
