### ISSUE TITLE
Styles no longer collapsable in editor

### ISSUE THREAD

**Issue by jamestowers** [styled-components/vscode-styled-components#94] opened 2018-06-14 14:31 UTC
I can no longer collapse the styles in the editor since the last vscode update 1.24.1

See the attached screenshot, the little - is no longer appears when you hover over the left edge

![screen shot 2018-06-14 at 15 26 37](https://user-images.githubusercontent.com/1722000/41418493-b7e960a8-6fe7-11e8-8401-569eb5447285.png)

**Comment by mjbvz** [comment] 2018-06-14 23:16
Unrelated to this extension. Root cause is the change to syntax based folding (see [vscode 1.24 release notes](https://code.visualstudio.com/updates/v1_24#_syntax-aware-folding-enabled-by-default-for-jsts))

Duplicate of https://github.com/Microsoft/TypeScript/issues/23382

**Closed by mjbvz** 2018-06-14 23:16 UTC
