### ISSUE TITLE
Lint error with multiple template literals in one line

### ISSUE THREAD

**Issue by phucanhapril** [styled-components/vscode-styled-components#134] opened 2018-09-16 19:25 UTC
Might be related to [issue 133](https://github.com/styled-components/vscode-styled-components/issues/133)

This input
<img width="368" alt="screen shot 2018-09-16 at 3 22 24 pm" src="https://user-images.githubusercontent.com/6667278/45600047-69873f80-b9c4-11e8-9a0d-cba4b33f675d.png">

gives me these errors
<img width="414" alt="screen shot 2018-09-16 at 3 22 18 pm" src="https://user-images.githubusercontent.com/6667278/45600046-655b2200-b9c4-11e8-8f96-d8bc97cb946f.png">

Btw I'm not using a `ThemeProvider`, just importing `themes.js` into my file (for personal reasons I find the whole `${({ theme }) => theme.etc` crowds up my code)

**Comment by mjbvz** [comment] 2018-09-17 22:57
Duplicate of #133

**Closed by mjbvz** 2018-09-17 22:57 UTC
