### ISSUE TITLE
Syntax highlighting broken for `StyledThing.extend`

### ISSUE THREAD

**Issue by maartenth** [styled-components/vscode-styled-components#166] opened 2019-04-08 08:28 UTC
Apart from issue #162 (syntax highlighting for inline functions), also `.extend` styles are not highlighted:

![Screen Shot 2019-04-08 at 10 24 49](https://user-images.githubusercontent.com/298893/55709652-153bbf80-59e9-11e9-92ae-6a08fd0614d3.png)

**Comment by maartenth** [comment] 2019-04-08 15:05
And syntax highlighting is also broken for type literals with newlines (and no semicolons or commas):

![Screen Shot 2019-04-08 at 17 02 49](https://user-images.githubusercontent.com/298893/55734774-7632ba00-5a20-11e9-8f80-356cec1c1080.png)

**Comment by joeytwiddle** [comment] 2019-05-28 02:37
I created [a small bounty](https://www.bountysource.com/issues/72534490-syntax-highlighting-broken-for-styledthing-extend) for this issue (~21 USD).

**Comment by Ale-cc** [comment] 2020-01-20 03:37
So do i.
![image](https://user-images.githubusercontent.com/18302674/72697003-4270ed00-3b79-11ea-950d-2f53bddfdcb4.png)

**Comment by jasonwilliams** [comment] 2020-10-09 10:50
Closing as dupe of https://github.com/styled-components/vscode-styled-components/issues/87

**Closed by jasonwilliams** 2020-10-09 10:50 UTC
