### ISSUE TITLE
CSS is showing HTML tags as suggestion

### ISSUE THREAD

**Issue by akshay2739** [styled-components/vscode-styled-components#385] opened 2022-11-23 03:48 UTC
Type: <b>Bug</b>

Download vscode-styled-component and try to use intellisense for any CSS property in template literal of jsx

Extension version: 1.7.5
VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.15.0-53-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|13.38GB (5.56GB free)|
|Process Argv|--unity-launch --crash-reporter-id 480d450a-fc6c-4ee8-adae-2d96c46fd227|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by jasonwilliams** [comment] 2022-11-23 08:35
Could you have a look through this issue and tell me if anything in there resolves it https://github.com/styled-components/vscode-styled-components/issues/191

**Comment by akshay2739** [comment] 2022-11-24 04:02
Actually, it is a little different error than mine. It is showing CSS suggestion in #191 but in my case it is not showing no CSS property at all. It is just showing HTML tags only.

**Comment by jasonwilliams** [comment] 2022-11-24 10:33
@akshay2739 can you give me some steps to reproduce this?

**Comment by jasonwilliams** [comment] 2022-12-15 09:56
Closing due to lack of information

**Closed by jasonwilliams** 2022-12-15 09:56 UTC

**Comment by MenaiAla** [comment] 2023-01-04 00:40
The same issue. Any solution.

Original issue: [source](https://github.com/styled-components/styled-components/issues/3910)
