### ISSUE TITLE
Highlighting and autocomplete not working for new way to specify props in TypeScript

### ISSUE THREAD

**Issue by uucue2** [styled-components/vscode-styled-components#98] opened 2018-06-21 14:37 UTC
styled-components v3.3.3 (paired with typescript v2.9.1) now lets us specify props in a slightly cleaner way. However, if i use the new technique, i lose the highlighting and autocomplete features from this plugin. See `NewButton` below:

![image](https://user-images.githubusercontent.com/12840079/41725491-8f1170aa-7535-11e8-8f01-d26e3dea937b.png)

Linting still seems to be working, though:

![image](https://user-images.githubusercontent.com/12840079/41725557-b0a70c98-7535-11e8-83b8-55cc48aee71b.png)

**Comment by Cu3PO42** [comment] 2018-06-21 16:00
Duplicate of #81.

**Closed by Cu3PO42** 2018-06-21 16:00 UTC
Labels: duplicate, enhancement, injection-grammar
