### ISSUE TITLE
Fuzzy input matching like `tac` expands to `text-align: center`

### ISSUE THREAD

**Issue by deadcoder0904** [styled-components/vscode-styled-components#69] opened 2018-03-16 11:04 UTC
Integrating this with Emmet abbreviation. I normally write CSS like this 😂

![37131011-30e9a4b8-223b-11e8-9ed1-4ccc8f32c385](https://user-images.githubusercontent.com/16436270/37517568-e561137e-2937-11e8-84fe-6d466c866ccf.gif)

**Comment by mjbvz** [comment] 2018-03-16 17:02
The root cause is a limitation of the typescript-styled-extension. See this note https://github.com/Microsoft/typescript-styled-plugin#emmet-in-completion-list

Closing this as upstream - https://github.com/Microsoft/typescript-styled-plugin/issues/41

**Closed by mjbvz** 2018-03-16 17:02 UTC

**Comment by alvinsight** [comment] 2019-07-05 13:47
Hello, it seems the upstream issue is fixed but the completions still aren't at the top:
<img width="941" alt="Screenshot 2019-07-05 at 09 46 17" src="https://user-images.githubusercontent.com/4254030/60726538-592c5b00-9f2b-11e9-94e8-e1b892b7aa9d.png">
