### ISSUE TITLE
intelisense is not working (only happening on the 1.7.0 version)

### ISSUE THREAD

**Issue by willian-lemann** [styled-components/vscode-styled-components#341] opened 2021-12-10 15:15 UTC
**Screenshot**
![image](https://user-images.githubusercontent.com/44612750/145596530-7134b89c-9180-4d8e-a2e0-ae86252de109.png)

**To Reproduce**
try to write whatever css atribute it will not complete with the intelisense, as example: "back" it does not return "background-color" or "background" in the intelisense

   
- Extension Version [e.g. 1.7.0]

**Additional context**

**Comment by keithtxw** [comment] 2021-12-10 15:22
Same issue. I can confirm 1.6.6 works.

**Comment by willian-lemann** [comment] 2021-12-10 15:30
let's wait till the fix, and till happen 1.6.6 was already working really good so..

**Comment by douglaschalegre** [comment] 2021-12-10 15:42
Is there a way to rollback to 1.6.6 for a temporary solution?

**Comment by wpicard-nexapp** [comment] 2021-12-10 15:58
> Is there a way to rollback to 1.6.6 for a temporary solution?

Yes, it is possible to rollback to the previous version:
![image](https://user-images.githubusercontent.com/79542205/145603235-8aeb244b-9bba-4797-9bc6-6a5efd566c7d.png)

**Comment by jasonwilliams** [comment] 2021-12-10 16:38
This is a duplicate of https://github.com/styled-components/vscode-styled-components/issues/339 please move discussion there.

**Closed by jasonwilliams** 2021-12-10 16:38 UTC
Labels: bug
