### ISSUE TITLE
All custom patterns/tags via vscode configuration

### ISSUE THREAD

**Issue by PssbleTrngle** [styled-components/vscode-styled-components#273] opened 2021-03-03 16:33 UTC
**Describe the bug (including copyable syntax)**
At the moment, the vscode plugin allows to enable matching for custom tags,
but the highlighting is not able to be configured for custom patterns.

**Expected behavior**
It would be great if there was a possibility to configure custom tags or even patterns in the vscode settings of a project.

**Comment by jasonwilliams** [comment] 2021-05-18 18:40
Unless it can be figured out via https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide i don't see this being possible. 

Ill leave it open as a future enhancement but it would be difficult to dynamically update the syntax based on custom tags.

**Comment by jasonwilliams** [comment] 2021-07-26 09:43
Closing as a duplicate of https://github.com/styled-components/vscode-styled-components/issues/303

**Closed by jasonwilliams** 2021-07-26 09:43 UTC
Labels: enhancement
