### ISSUE TITLE
Support React-Native properties

### ISSUE THREAD

**Issue by bluenex** [styled-components/vscode-styled-components#91] opened 2018-05-28 10:26 UTC
If I understand correctly, this property is only available for React Native. Even though the plugin warns for `[ts-styled-plugin] Unknown property: 'tint-color'` but a snippet below renders correctly.

```jsx
const Icons = styled.Image.attrs({
	source: props => props.type,
})`
	tint-color: ${props => props.color ? props.color : 'black'};
	width: ${props => props.width ? props.width : 15};
	height: ${props => props.height ? props.height :15};
`;
```

**Comment by Cu3PO42** [comment] 2018-05-31 07:53
As the error message indicates, this is actually a problem with `ts-styled-plugin` which comes bundled with this plugin and not this plugin directly. Please raise an issue [there](https://github.com/Microsoft/typescript-styled-plugin) as well, so we can track it here.

**Comment by mjbvz** [comment] 2018-07-10 22:19
Tracked by https://github.com/Microsoft/typescript-styled-plugin/issues/58

**Comment by jasonwilliams** [comment] 2020-10-08 18:31
For intellisense we need to add react-native properties to the css language service, example here:
https://github.com/microsoft/vscode-css-languageservice/blob/716292720c09f444167fd5528bcd4e6d1c6cc5db/src/test/css/lint.test.ts#L123-L125

This needs to be PRd into https://github.com/microsoft/typescript-styled-plugin

**Comment by bleszerd** [comment] 2021-03-22 17:50
Any news about that? I still have the same problem

**Comment by jasonwilliams** [comment] 2021-05-14 22:15
Closing as the issue is upstream

**Closed by jasonwilliams** 2021-05-14 22:15 UTC
Labels: Hacktoberfest, blocked, bug, help wanted, upstream
