### ISSUE TITLE
Some styles props React Native ex: resize-mode

### ISSUE THREAD

**Issue by nikosantis** [styled-components/vscode-styled-components#221] opened 2020-05-25 20:48 UTC
I have a warn with resize-mode in Native:
Unknown property: 'resize-mode'

Thanks

**Comment by vinifraga** [comment] 2020-07-03 19:33
I'm also receiving this warning. Any news on this one?

![image](https://user-images.githubusercontent.com/37725197/86494285-f2629d00-bd4a-11ea-8f3b-ef0a73cc5808.png)

**Comment by felix-sebastian** [comment] 2020-09-06 03:31
bump 🙏 
@tadhglewis

**Comment by jasonwilliams** [comment] 2020-10-08 18:17
Dupe of https://github.com/styled-components/vscode-styled-components/issues/91

**Closed by jasonwilliams** 2020-10-08 18:17 UTC

**Comment by ProgramadorLeandroSantos** [comment] 2022-01-17 04:38
Hey dude, we can just add an atribute on ImageComponent like this:
` resizeMethod="resize"`

tell me if works for you ;)

**Comment by josuenm** [comment] 2022-08-27 23:45
Use this example: 
```
export const Picture = styled.Image.attrs({ 
  resizeMode: "cover" 
})`
  // Your style
`
```
