### ISSUE TITLE
Intellisense not working

### ISSUE THREAD

**Issue by Delice0** [styled-components/vscode-styled-components#347] opened 2021-12-18 01:47 UTC
**Describe the bug (including copyable syntax)**
If you're planning on posting a screenshot, please paste the accompanying code here.

- Intellisense is not working. Simple as that.

**Screenshot**
Screenshots are alway useful!
![x](https://user-images.githubusercontent.com/59118341/146624974-c96e4ce2-78f7-4dc3-80f9-bdc9e95f0fc2.PNG)

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.
If you showed a screenshot, it will help a lot to paste accompanying code which matches

- Style a simple div e.g. css height property.

**Expected behavior**
Explain what you expected to happen, and what is happening instead.

- I expect the intellisense to tell me that an height css property exists.

**Build environment (please complete the following information):**

- OS: [Windows 10]
- VSCode Version: [1.63.2]
- Extension Version [0.0.31]

**Additional context**

**Comment by jasonwilliams** [comment] 2021-12-18 08:13
> Extension Version [0.0.31]

?
This is super old..
Make sure you’re using the right version, please read the readme of this repo. 

https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components

**Comment by Jetandarkumar** [comment] 2021-12-18 14:11
why I am unable to find this extension in vs code extensions search

**Comment by ragnarr18** [comment] 2021-12-20 09:03
I too have been having the same problam with this extension, like 2 weeks ago it was working great but now it just stopped working.

**Comment by jasonwilliams** [comment] 2021-12-20 09:16
@ragnarr18 please show a screenshot of your version

**Comment by jasonwilliams** [comment] 2021-12-20 09:16
> why I am unable to find this extension in vs code extensions search

If you can’t find it just download it from the marketplace

**Comment by ragnarr18** [comment] 2021-12-20 09:19
@jasonwilliams 
![image](https://user-images.githubusercontent.com/42973395/146743278-cc127f81-2333-4790-8f5c-bbef4215fc9c.png)

**Comment by jasonwilliams** [comment] 2021-12-20 09:29
@ragnarr18 do you have a snippet or gif of it not working?

**Comment by ragnarr18** [comment] 2021-12-20 09:40
Sry Im having trouble doing it right now, will get back to you later on it. Basically no suggestions from vscode, but it still highlights css properties.

**Comment by ragnarr18** [comment] 2021-12-20 13:34
So now, 4 hours later it starts working as intended! With maybe the exception of this error message.
![image](https://user-images.githubusercontent.com/42973395/146774851-bf23ff6e-2f65-4d82-8cd1-72ec714064a6.png)

**Comment by jasonwilliams** [comment] 2021-12-20 14:28
What’s your language set to on the bottom? Can you paste a snippet of that screenshot?

**Comment by ragnarr18** [comment] 2021-12-20 14:58
![image](https://user-images.githubusercontent.com/42973395/146787276-343b4440-d437-49e2-a9f3-cc566a50752b.png)
@jasonwilliams

**Comment by jasonwilliams** [comment] 2021-12-20 18:40
You need to be on javascriptreact or set your file extension to be .jsx which should trigger it. Does that help?

**Comment by tobz1000** [comment] 2021-12-21 00:41
I've also been experiencing this for the last few days. I was on version 1.7.0 (not sure why I wasn't prompted to update to 1.7.2).

I manually uninstalled and reinstalled to (v1.7.2), and intellisense is working again. Maybe this'll work for other people too?

**Comment by ragnarr18** [comment] 2021-12-21 10:14
@jasonwilliams sorry for a late reply, I changed the file extension to jsx that didnt help, then I used the javascript React language mode with no luck. Im really loving the help tho! I also tried @tobz1000 idea with no luck, maybe there is just something missing on my end.

**Comment by Bugrabugra** [comment] 2021-12-22 08:10
Hello there. I came here to open an issue for this but can you please confirm that you have an code like that:

![image](https://user-images.githubusercontent.com/16042461/147058014-cf0630d2-805e-4208-90d9-d96a06fe68f4.png)

Because I realized that if you have a code importing another styled component like this, intellisense fails and never works again for this .jsx file. Even HTML Emmet is not working. And also CSS intellisense fails.

When I change the " styled(ANOTHER COMPONENT)`` " to " styled.div`` " everything works great again. So I can say that importing another component fails the intellisense.

**Comment by emmiz** [comment] 2021-12-23 08:39
I have the same problem with intellisense not working for styled-components. I've attached a video where you can see the behaviour as well as all my installed extension if that might help.

@Bugrabugra Yes I do have styled components that I try to add extra styling to in other files like in my example in the attached video.

OS: [Windows 10]
VSCode Version: [1.63.2]
Extension Version [1.7.2]

https://user-images.githubusercontent.com/13101861/147212709-cdbd8c54-6dcb-4759-b473-ef72d71297f7.mp4

**Comment by jasonwilliams** [comment] 2021-12-23 10:14
Thanks for the info @emmiz 

I've just tested 1.7.2 with `Styled(Component)` and i still get auto complete so I'm not able to reproduce this issue, nor do I think its related to that issue.

Are one of you able to make a test case repo I can try this out on?

**Comment by Repugraf** [comment] 2021-12-24 10:12
@jasonwilliams I have the similar issue.
For some reason extension treats templated literal block as jsx and not like css.

Note: I'm using typescript and extension of a file is TypeScript React

<img width="975" alt="Screenshot 2021-12-24 at 12 10 45" src="https://user-images.githubusercontent.com/43890857/147343688-13bd474c-78c5-4054-bd0d-73a5be4e4d9c.png">

<img width="450" alt="Screenshot 2021-12-24 at 12 10 53" src="https://user-images.githubusercontent.com/43890857/147343726-8828f792-8b39-46da-87fe-d2b7e4f1144a.png">

**Comment by jasonwilliams** [comment] 2021-12-24 10:42
@Repugraf see https://github.com/styled-components/vscode-styled-components#emmet-is-auto-completing-html-tags-instead-of-css

**Comment by jasonwilliams** [comment] 2021-12-24 10:47
This problem seems to be affecting some but not others. I can’t reproduce it and the low volume here makes me think not everyone is seeing this. It may be some conflicting settings or extensions.

we will need a very small test case repo to move this forward. If @ragnarr18 could make that it would be great

**Comment by ragnarr18** [comment] 2021-12-24 12:29
@jasonwilliams https://github.com/ragnarr18/temp-repo, in my case you can see it in /pages/posts/post.tsx

**Comment by ragnarr18** [comment] 2021-12-30 11:04
Maybe this has something to do with typescript projects or Nextjs projects? I got it fully working on a create-react-app project

**Comment by hannanel100** [comment] 2021-12-30 19:11
> 

I have it working in a cra-typescript project and for a teammate of mine its not working...

**Comment by Jhonatan-atalaya** [comment] 2022-01-03 13:59
#### A possible soluction:
I had the same problem and it was fixed by updating VSCode.
Before updating VSCode, adding the extension installed version __1.7.0__ after updating VSCode, the extension was updated to version __1.7.2__ and everything worked correctly.

*current version of VSCode: __1.63.2__
*Operating system: __linux mint__
*technology: __React with Typescript__

**Comment by Jhonatan-lezcano** [comment] 2022-01-03 14:01
####A possible soluction:
I had the same problem and it was fixed by updating VSCode.
Before updating VSCode, adding the extension installed version __1.7.0__ after updating VSCode, the extension was updated to version __1.7.2__ and everything worked correctly.

*current version of VSCode: __1.63.2__
*Operating system: __linux mint__
*technology: __React with Typescript__

**Comment by ragnarr18** [comment] 2022-01-03 14:09
> #### A possible soluction:
> I had the same problem and it was fixed by updating VSCode.
> Before updating VSCode, adding the extension installed version __1.7.0__ after updating VSCode, the extension was updated to version __1.7.2__ and everything worked correctly.
> 
> * current version of VSCode: __1.63.2__
> * Operating system: __linux mint__
> * technology: __React with Typescript__

Updating VScode did the trick

**Closed** 2022-01-03 20:14 UTC
Labels: bug, more info

**Comment by hannanel100** [comment] 2022-01-09 09:30
Thanks, it did the trick!

**Comment by Crazy4Dumplings** [comment] 2022-01-14 14:48
I was having the same issue while implementing the styled components but I was importing "styledcomponents" instead of styled.

Syntax Highlighting is specifically made to work with styled so make sure your default import is "styled" and nothing else.
Hope it helps!

**Comment by GooBall** [comment] 2022-01-16 14:39
The intellisense was only broken for me on nextjs projects. My VSC was up-to-date but the extension was on 1.7.0 and nothing to say there was a newer version available.

Uninstalling and reinstalling the extension seems to have fixed the broken intellisense and the installed extension version is now 1.7.2 🤷🏼

**Comment by jurchfield** [comment] 2022-01-27 18:56
My VSCode was up-to-date, but `vscode-styled-components` was still 1.7.0.

I can confirm that uninstalling 1.7.0 and reinstalling 1.7.2 fixed the issue for me in a CRA TypeScript project.

**Comment by nyuuke** [comment] 2022-02-05 12:41
still having this issue, last vscode update and installing styled-components extension numerous times. it started with using typescript now even with a JS managed project it does not gives the autocomplete.

**Comment by Deknoinarak** [comment] 2022-02-05 12:41
I having the same issue in vs code 1.64.0
![image](https://user-images.githubusercontent.com/60281096/152642526-695e9b53-a511-4555-bd0b-97cd453e5375.png)

I try open this project on another device with the same setting the same extension and it worked.

**Comment by Deknoinarak** [comment] 2022-02-05 12:42
But my another device is Linux mint but my computer that having this issue is windows 10

**Comment by jasonwilliams** [comment] 2022-02-05 13:45
Duplicate of https://github.com/styled-components/vscode-styled-components/issues/354 please move conversation there

**Comment by tanshiyang** [comment] 2022-02-08 07:22
![动画](https://user-images.githubusercontent.com/2681340/152935644-71ae9108-b39c-4dd8-a151-850f024274db.gif)
![Uploading 动画.gif…]()
I having the same issue in vs code 1.64.0 with plugin v1.7.2

**Comment by jasonwilliams** [comment] 2022-02-08 08:00
@tanshiyang see other issue. I’m locking his as it’s a duplicate
