### ISSUE TITLE
styled-components-breakpoint highlighting

### ISSUE THREAD

**Issue by svictoreq** [styled-components/vscode-styled-components#79] opened 2018-04-11 21:48 UTC
When using `${breakpoint(<device>)}`, you loose syntax highlighting.

<img width="378" alt="screenshot 2018-04-11 17 43 29" src="https://user-images.githubusercontent.com/29575744/38644908-38c22eea-3db0-11e8-9af0-4713ee4a7266.png">

**Comment by Cu3PO42** [comment] 2018-04-12 10:05
The syntax highlighting is triggered by certain variable names for the tags as a heuristic. The thing about media templates is that you can give them any name you like.

This plugin currently supports the name `media` for those queries since that is used by the styled-components docs. Unfortunately it is impossible to have an exhaustive list of names that people might choose.

I understand you are using [this library](https://github.com/jameslnewell/styled-components-breakpoint) which suggests the breakpoint name. I am, however, unsure if a library warrants the addition of another special case to the grammar, but it's something that can be considered. What's your opinion on this @julienp?

It might be a sensible long term goal to make the keywords triggering the syntax highlighting more configurable, but I believe that's not in the near future.

**Comment by jorgesuarezch** [comment] 2019-12-09 12:01
Hey there, thank you for this awesome plugin.
Just wondering if this can be added to the documentation. In a section called supported tags or something.  So everyone would know what is supported by the plugin.

**Comment by jasonwilliams** [comment] 2020-10-09 09:26
dupe of https://github.com/styled-components/vscode-styled-components/issues/164

**Closed by jasonwilliams** 2020-10-09 09:26 UTC
Labels: Hacktoberfest, injection-grammar
