### ISSUE TITLE
Auto-complete moves the cursor back by a letter

### ISSUE THREAD

**Issue by Gaulepal** [styled-components/vscode-styled-components#294] opened 2021-05-20 13:16 UTC
Issue Type: <b>Bug</b>

=> I'm facing this issue since yesterday. I disable all other extensions to confirm the issue.
   
- Auto-complete moves the cursor back by a letter

Extension version: 1.6.1
VS Code version: Code 1.56.2 (054a9295330880ed74ceaedda236253b4f39a335, 2021-05-12T17:44:30.902Z)
OS: macOS Big Sur (20E241)

=> Please have a look for an issue that I'm facing.

![may be a bug](https://user-images.githubusercontent.com/13852493/118993212-9cf4a600-b985-11eb-87b1-d6241d35e698.gif)

**Comment by Gaulepal** [comment] 2021-05-20 14:08
![may be a bug](https://user-images.githubusercontent.com/13852493/118993054-7afb2380-b985-11eb-963f-c77c513402f4.gif)

**Comment by jasonwilliams** [comment] 2021-05-20 15:17
Dupe of https://github.com/styled-components/vscode-styled-components/issues/291

**Closed by jasonwilliams** 2021-05-20 15:17 UTC
