### ISSUE TITLE
inside "injectGlobal"  style hinting not working !

### ISSUE THREAD

**Issue by MpMeetPatel** [styled-components/vscode-styled-components#82] opened 2018-04-23 04:58 UTC
Style hinting is working inside "Styled" but not working inside "injectGlobal"

example : 

// Hinting is not coming here 

```

injectGlobal`
*,
*::after,
*::before {
  padding: 0;
  margin: 0;
  box-sizing: inherit;
  font-family: 'Nunito', 'Fascinateserif', sans-serif;
}

html {
  font-size: 16px;
  color: #fff;
}`


```
// Hinting is showing here

```

const Button = styled.button`
   color: red;
`


```

**Comment by Cu3PO42** [comment] 2018-05-05 21:19
I assume that by hinting you mean the auto-completion provided by `ts-styled-plugin`. In this case this is a duplicate of #68. Follow the instructions there to enable IntelliSense.

**Closed by Cu3PO42** 2018-05-05 21:19 UTC
