### ISSUE TITLE
Preventing autocompletion from other plugins with command 'extension.insertColonOrSemiColon' not found

### ISSUE THREAD

**Issue by DavideDaniel** [styled-components/vscode-styled-components#313] opened 2021-07-13 19:30 UTC
**Describe the bug (including copyable syntax)**
Attempting to write an import statement and the styled-components plugin is preventing auto completion from other plugins. The error notification via vscode says: 
``` command 'extension.insertColonOrSemiColon' not found ```

**Screenshot**
Reverting to a month back and using 1.5.2 worked though I did not try to incrementally go back each version from 1.6.4. I've just been noticing this error for a little bit and this was the fastest way to get back to a working state. 
![image](https://user-images.githubusercontent.com/8802938/125513384-40c3aae5-d67b-4933-b669-34e16926d801.png)

**To Reproduce**
Steps to reproduce the issue, or JavaScript code that causes this failure.

**Expected behavior**
Should not interrupt autocompletion from other plugins. Probably should not edit non `styled` code maybe.

**Build environment (please complete the following information):**

- OS: macOS Catalina 10.15.7
- VSCode Version: 1.58.1
- Extension Version: 1.6.4

**Additional context**

**Comment by jasonwilliams** [comment] 2021-07-13 20:14
@DavideDaniel what file type is this happening on and what extension is it blocking?

**Comment by brunofamiliar** [comment] 2021-07-21 00:08
Hi, I have the same problem. In my case it occurs in a javascript file

**Comment by jasonwilliams** [comment] 2021-07-21 00:13
I’d be interested in a test case for this if you can put one together?

**Comment by brunofamiliar** [comment] 2021-07-21 00:53
Forgive my english. 

1-) Create a javascript file
2-) Type a word and wait for the autocomplete to suggest
3-) Press the Enter key
4-) Problem is presented

![image](https://user-images.githubusercontent.com/32016729/126413121-6f944d7a-b32c-4ad4-bc43-cba4b1cf6314.png)

**Visual Code Info**
![image](https://user-images.githubusercontent.com/32016729/126413407-868f4183-1003-4e6d-b9cd-1a0e6099d2e8.png)

**Comment by jasonwilliams** [comment] 2021-07-24 14:07
@brunofamiliar i still can't reproduce this issue, could you make a test case repo?
The javascript files ive toyed with work fine

**Comment by brunofamiliar** [comment] 2021-07-24 15:15
Hi, I restarted vscode and the problem is no longer there. 🤔🤔

**Comment by jasonwilliams** [comment] 2021-07-26 09:39
How about you @DavideDaniel  ?

**Comment by jasonwilliams** [comment] 2021-09-02 21:15
Im closing this for now, please re-open if it happens again

**Closed by jasonwilliams** 2021-09-02 21:15 UTC
Labels: bug, E-Easy, more info
