### ISSUE TITLE
Generics support for typescript

### ISSUE THREAD

**Issue by nicholasrq** [styled-components/vscode-styled-components#114] opened 2018-07-13 12:42 UTC
When creating dynamic components we often use generics syntax to define types for props.

We're doing it like so:

```typescript
const MyComponent = styled<SomeProps>`
  color: ${(p) => p.isActive ? 'red' : 'blue'};
`

const MyOtherComponent = MyComponent.extend<OtherProps>`
  color: ${(p) => p.isFocused ? 'red' : 'blue'};
`
```

Yes, `vscode-styled-components` supports _some_ of the generics, but with current support it's impossible to extend extend other components, only built-in elements because this following will not pass TS type validation:

```typescript
const MyComponent = styled<MyProps>(NotAStyledComponent)`
  color: ${(p) => p.isActive ? 'red' : 'blue'};
`

// these two also will cause validation error
const MyComponent = styled<MyProps, NotAStyledComponent>(NotAStyledComponent)`
  color: ${(p) => p.isActive ? 'red' : 'blue'};
`

// even if styled component passed
const ComponentOne = styled.div`
  background-color: #fff;
`

// both will fail
const MyComponent1 = styled<MyProps, ComponentOne>(ComponentOne)`
  color: ${(p) => p.isActive ? 'red' : 'blue'};
`

const MyComponent1 = styled<MyProps>(ComponentOne)`
  color: ${(p) => p.isActive ? 'red' : 'blue'};
`
```

We sure can do something like this:

```typescript
const MyComponent1 = styled<MyProps, any>(ComponentOne)`
  color: ${(p) => p.isActive ? 'red' : 'blue'};
`
```

But it will eventually force us to use `any` in all underlying code or will break its validation otherwise.

It would be great if you'll introduce generics support :)

**Comment by jacobarvidsson** [comment] 2018-08-08 13:11
For me it doesn't work for built in elements either.

**Comment by diegohaz** [comment] 2018-08-16 08:57
This is what I'm getting. Is there a way to fix it?
![image](https://user-images.githubusercontent.com/3068563/44198997-4e04ec80-a119-11e8-8104-4312d96bf2fc.png)

**Comment by DevanB** [comment] 2018-10-17 19:56
This seems to be an issue still.

Intellisense  suggestions stop working and code themeing changes too. Attached is a video of what I'm seeing.


![ezgif com-crop](https://user-images.githubusercontent.com/354652/47112761-4353fa00-d225-11e8-8e45-9da02e23f0d0.gif)

**Comment by osdiab** [comment] 2018-10-19 17:29
I think this is a duplicate of #81 , and is fixed by #101 , but that PR went stale.

**Comment by osdiab** [comment] 2018-10-19 17:36
As of now it gets even hairier if you have nested generics, too, like so:

```typescript
styled.button<Pick<ButtonProps, "size">>`
  font-size: ${props => fontSizeForButtonSize(props.size));
`
```

To keep in mind for how to design this regex.

**Comment by rlesniak** [comment] 2018-10-31 11:30
How things are going on this _basic_ feature?

**Comment by declanelcocks** [comment] 2018-11-01 02:05
Same as @DevanB for me. The highlighting is completely lost after adding in something like `<Props>`, `styled(Something)` or any other TS typings.

**Comment by Kovensky** [comment] 2018-11-01 02:10
It would already be helpful even if _only_ the base case of `<Identifier>` was supported. You can work around that with:

```ts
type StyledButtonProps = Pick<ButtonProps, 'size'>>
styled.button<StyledButtonProps>`
  font-size: ${props => fontSizeForButtonSize(props.size));
`
```

**Comment by jperelli** [comment] 2020-03-12 19:16
after a couple of hours trying to make this work... I realized of a too-simple-to-be-true workaround
```
// antd -> Table is a generic component
import styled from 'styled-components'
import { Table as AntdTable } from 'antd'

export const Table = styled(AntdTable)`
....
` as typeof AntdTable
```
posting it here just in case it helps someone, or myself in the future :)

**Comment by maxijonson** [comment] 2020-08-01 19:35
@jperelli Doing this no longer makes it a `StyledComponent` (for typings only of course!). This means that you would not be able to use them as a selector in tagged templates:

```tsx
const Component = (props: { title: string }) => <div {...props} />;
const StyledComponent = styled(Component)`
    position: relative;
` as typeof Component;

const Test = styled.div`
    ${Component} > { /* Typing error. Type 'Element' is not assignable to type 'CSSObject' */
        position: relative;
    }
`;
```

However, you could re-cast it into a `StyledComponent` and it would work OK

```tsx
const Test = styled.div`
    ${Component as StyledComponent<typeof Component, any, {}, never>} > {
        position: relative;
    }
`;
```

Are there better ways of using your solution without having to cast inside tagged templates? How can we make it recognized as a StyledComponent for the tagged templates?

Maybe there are some other typing limitations of removing the `StyledComponent` type, but that is just the first issue I've had when casting it.

**Comment by jasonwilliams** [comment] 2020-10-08 17:04
Closing as the main issue here was fixed in https://github.com/styled-components/vscode-styled-components/pull/101 please re-open if there's a new issue

**Closed by jasonwilliams** 2020-10-08 17:04 UTC
