### ISSUE TITLE
Selecting Intellisense suggestion results in doubled content being typed

### ISSUE THREAD

**Issue by paprikman** [styled-components/vscode-styled-components#325] opened 2021-09-13 07:34 UTC
**Describe the bug (including copyable syntax)**
I see this as a one solid issue, symptoms of which are being solved in other issues. This is a continuation of this https://github.com/styled-components/vscode-styled-components/issues/219.
Namely, the Intellisense in styled-components code won't account for previously typed text when making suggestions and completions. I will describe it in several examples below.

1. Start creating some pseudo styling like `after`, `selection`, etc.
![image](https://user-images.githubusercontent.com/57448756/133040751-176424fc-c070-4128-bd12-2f4a2c637ba9.png)
After hitting `ENTER` you will get this
![image](https://user-images.githubusercontent.com/57448756/133040821-866d60a2-d780-4b3b-83f6-ba544b0529b5.png)

2. If you start typing some css, Intellisense box would pop-up, close it and continue typing again. Say, it was `flex-` before. After applying the suggested option, say, `flow`, you will get `flex-flex-flow` (so the previously typed text is not accounted).

This is happening to me since early versions (below 1.0) of the extension.

**Expected behavior**
The behavior should be identical with regular `css` files.

**Build environment (please complete the following information):**

- OS: ubuntu 18.04 or windows 10, both using the same versions of vscode and extension.
- vscode@1.59.1
- vscode-styled-components@1.6.6 (or other versions, does not matter)

**Comment by ethernal** [comment] 2021-11-04 20:42
This is so very annoying. Any idea how to help fix the issue? Any suggestions (accurate) where to start? I have the same problem with ex. `max-` etc ends up as `max-max-width`.

**Comment by ethernal** [comment] 2021-11-04 20:52
Would adding support for Insert Mode API fix the issue? See: https://code.visualstudio.com/updates/v1_40#_support-intellisense-replace-mode

**Comment by jasonwilliams** [comment] 2021-11-04 21:06
> This is so very annoying. Any idea how to help fix the issue? Any suggestions (accurate) where to start? I have the same problem with ex. `max-` etc ends up as `max-max-width`.

Yes, there’s a lot you can do to help.

the first step is to see if older versions of VSCode remove this issue:
https://github.com/styled-components/vscode-styled-components/issues/322#issuecomment-940461254

My investigation is in that thread, it’s been raised with VSCode as I couldn’t get it working with older versions of the extension.

so I would ask you this:
1. Can you get it working with an older version of the extension?
2. Can you get it working with an older version of code
3. If the answer to both of those questions is no, it will be a case of digging into the internals of VSCode (which I’ve been doing) and seeing why it’s happening. I can help with that so ask any questions.


Finally, I might close this thread, because it’s a duplicate of the one I linked. Please confirm if that’s the cass

**Comment by jasonwilliams** [comment] 2021-11-04 21:41
> Would adding support for Insert Mode API fix the issue? See: https://code.visualstudio.com/updates/v1_40#_support-intellisense-replace-mode

Looks great, I’ve not seen that before. Maybe it could work sure. The api is called from typescript_styled_plugin. Once setup you’ll see

**Comment by paprikman** [comment] 2021-11-05 04:31
> Finally, I might close this thread, because it’s a duplicate of the one I linked. Please confirm if that’s the case

This is not a duplicate. The issue you have linked is only about a symptom of this comprehensive problem, as I have stated in the original post. There is a lot of issues that address particular problem and do not concern its origin in general.

I've had this thing for years since I have started using styled-components and its extension in vscode, so maybe like 2-3 years so far.

**Comment by jasonwilliams** [comment] 2021-11-05 08:25
> > Finally, I might close this thread, because it’s a duplicate of the one I linked. Please confirm if that’s the case
> 
> This is not a duplicate. The issue you have linked is only about a symptom of this comprehensive problem, as I have stated in the original post. There is a lot of issues that address particular problem and do not concern its origin in general.
> 
> I've had this thing for years since I started using styled-components and its extension in vscode, so maybe like 2-3 years so far.

Ok fair enough. My capacity is very stretched, so if someone else is able to do the investigation I layed out above that would help move this issue forward

**Comment by paprikman** [comment] 2021-11-05 08:34
> > > Finally, I might close this thread, because it’s a duplicate of the one I linked. Please confirm if that’s the case
> > 
> > 
> > This is not a duplicate. The issue you have linked is only about a symptom of this comprehensive problem, as I have stated in the original post. There is a lot of issues that address particular problem and do not concern its origin in general.
> > I've had this thing for years since I started using styled-components and its extension in vscode, so maybe like 2-3 years so far.
> 
> Ok fair enough. My capacity is very stretched, so if someone else is able to do the investigation I layed out above that would help move this issue forward

I should be able to finally get to this next month. I will make a PR if there's anything sensible.
@ethernal if you come up with something, please post it there as well, so that nobody is reinventing the wheel concurrently.

**Comment by jasonwilliams** [comment] 2021-11-09 12:44
Update 

I’ve raised here https://github.com/microsoft/typescript-styled-plugin/issues/153 as I feel the issue is more there than here.

Something that may unearth some clues is trying to do the same in native css and seeing what the css language server returns here https://github.com/microsoft/vscode-css-languageservice#development

then comparing that with what the typescript plug-in server does. 

There will be a difference somewhere.

**Comment by paprikman** [comment] 2021-11-12 05:37
> Update
> 
> I’ve raised here [microsoft/typescript-styled-plugin#153](https://github.com/microsoft/typescript-styled-plugin/issues/153) as I feel the issue is more there than here.

I should be able to test it this weekend.
There's also one more thing that I have experienced that adds to the point of this problem being related to the ts-server. Namely, if you use global properties like `props.theme` inside the `CreateGlobalStyle` method, then intellisense of the entire project gets incredibly slow. Exploring the debug log shows increased timings of ts compilation.

**Comment by jasonwilliams** [comment] 2021-11-13 09:22
@paprikman could you raise that as a separate issue with reproduction steps? Sounds like it could be something we raise with typescript.

Related issue raised with VSCode: 
https://github.com/microsoft/vscode/issues/134328

My theory is the suggestions have the wrong  start range, the start range is set to being where the cursor is, so it appends rather than replacing. Sadly I can’t prove this because I can’t get VSCode building properly: https://github.com/microsoft/vscode/issues/136978#event-5609820718

**Comment by paprikman** [comment] 2021-11-13 12:55
> @paprikman could you raise that as a separate issue with reproduction steps? Sounds like it could be something we raise with typescript.

Sure, I will test this once again and provide a minimal working example.

**Comment by jasonwilliams** [comment] 2021-11-17 09:08
@paprikman how did you get on, did you need any help?

**Comment by paprikman** [comment] 2021-11-17 09:31
> @paprikman how did you get on, did you need any help?

As for the slow intellisense with `css` and `props.theme` inside `CreateGlobalStyle`, I have created the issue, but making a MWE for it required too much time.

I have not tested https://github.com/styled-components/vscode-styled-components/issues/325#issuecomment-964117682 yet, it's been quite busy. I am definitely doing this as soon as I have a spare evening.

**Comment by karlhorky** [comment] 2021-11-17 16:00
@paprikman here are some further videos and content from the new issue I reported at #336 (didn't find your issue above due to searching for different keywords)

If you think any of this (eg. the videos) would be useful to add to your issue description at the top of this page, feel free!

---

**Describe the bug (including copyable syntax)**

1. When selecting any pseudo-classe from the VS Code autocomplete, two colons are entered incorrectly (pseudo-classes use a single colon)
2. When selecting any pseudo-element from the VS Code autocomplete, three colons are entered incorrectly (pseudo-elements use two colons)

Eg. entering either `:not` or `::before` and selecting the autocomplete item in VS Code results in incorrect code:

```js
const createNewCompanyStyles = css`
  display: flex;

  > div {
    margin-bottom: 32px;
  }
`;
```

**Video**

https://user-images.githubusercontent.com/1935696/142225245-07f5c9b4-c67f-42a7-9bb1-1aab32bd29fe.mp4


**To Reproduce**

Reproduction steps above

**Expected behavior**

Autocomplete entries should not result in incorrect CSS code

**Build environment (please complete the following information):**

- OS: macOS Monterey 12.0.1
- VSCode Version: 1.62.1
- Extension Version 1.6.6

---

Even worse, there's actually no way to escape from this bug (unless you do something tricky like copy/pasting code), because just continuing with the `(` after the `:not` causes the autocomplete item to be selected - and then you have an extra bracket pair too!! 😫

https://user-images.githubusercontent.com/1935696/142227266-9f41513c-0037-4c1d-a590-db7592739db6.mp4

**Comment by jasonwilliams** [comment] 2021-11-19 16:05
Ok I had some time today...

The good news is we have a new place to look:
https://github.com/microsoft/vscode/issues/134328#issuecomment-973593757

This is where VSCode receives the suggestions from the language server and decides what to do wit them.
First we can start with basic CSS.

This is the CSS I'm working with..

```css
div {
  accent-color: black;
  color: black;
  width: 100%| < cursor here (hitting ctrl + spacebar)
}
```

The bug, is that in styled components it appends another `100%` on the end, but in CSS it doesn't. 
lets take a look at how the CSS language server responds...


<img width="1192" alt="Screenshot 2021-11-19 at 14 28 55" src="https://user-images.githubusercontent.com/936006/142639207-3940f6cf-3a15-4d3d-93be-c1369e8042df.png">

The above is good, we can see that the editStart and the editInsertEnd match up with the 100% in the css. This explains why it works well,

Now lets take a look at the response from TypeScript Styled Plugin...

<img width="1347" alt="Screenshot 2021-11-19 at 14 18 14" src="https://user-images.githubusercontent.com/936006/142637893-ed304f20-e6f9-4670-a842-94138428869f.png">

This is interesting (and expected). the `editStart` value is set as where the cursor is. Causing the new snippet to be placed at the end (or duplicating as this ticket puts it).

I suppose we need to see what sets that value and why its wrong (where as the CSS one is correct).

_few hours later_

Well it looks like I've found the issue (somewhat), VSCode is falling back to the defaultRange. it seems the range gets lost somewhere between the language server and VSCode

<img width="1382" alt="Screenshot 2021-11-19 at 16 01 08" src="https://user-images.githubusercontent.com/936006/142653545-d3097295-0253-4a87-b019-58f51d96d7f7.png">

I think the culprit is here https://github.com/microsoft/typescript-styled-plugin/blob/main/src/_language-service.ts#L121-L138 because `item` has the range, but its never converted. So it just gets dropped

**Comment by jasonwilliams** [comment] 2021-11-19 19:24
I didn't manage to fix it sadly.
Looking at [CompletionInfo](https://github.com/microsoft/TypeScript/blob/64b8172f0688c7567f4a880754a7f972423f092a/src/services/types.ts#L1169-L1188) theres a new property [OptionalReplacementSpan](https://github.com/microsoft/TypeScript/blob/64b8172f0688c7567f4a880754a7f972423f092a/src/services/types.ts#L1169-L1188) I think maybe this needs adding. It could help with this issue

You can see we don't send it here:
https://github.com/microsoft/typescript-styled-plugin/blob/cd5903097be3e879051e4282ae7005ab1b41f199/src/_language-service.ts#L379-L392

**Comment by jasonwilliams** [comment] 2021-11-20 18:34
Fixed by: https://github.com/microsoft/typescript-styled-plugin/pull/156

**Closed** 2021-12-06 21:45 UTC
Labels: bug

**Comment by karlhorky** [comment] 2021-12-07 09:35
@jasonwilliams amazing, this is great that this got merged!

Will this be released in `vscode-styled-components` version `1.6.7`?

**Comment by jasonwilliams** [comment] 2021-12-07 14:03
This has been released in 1.7.0, it should be out now

**Comment by jasonwilliams** [comment] 2021-12-07 21:27
Can’t release yet, due to https://github.com/styled-components/vscode-styled-components/issues/338

**Comment by karlhorky** [comment] 2021-12-12 10:32
Just tried this out, and can confirm that `styled-components.vscode-styled-components@1.7.2` fixes this issue! 🎉

**Comment by paprikman** [comment] 2021-12-12 11:45
> Just tried this out, and can confirm that `styled-components.vscode-styled-components@1.7.2` fixes this issue! 🎉

Yes, it works now. Thanks @jasonwilliams for the great work!
