### ISSUE TITLE
After expand of Emmet snippet trigger keyword is not removed

### ISSUE THREAD

**Issue by myovchev** [styled-components/vscode-styled-components#58] opened 2018-02-19 13:48 UTC
Consider the following use case 

Before expanding
```js
const Element = styled.div`
    pos:f
`;
```

After expanding
```js
const Element = styled.div`
    pos:position: fixed;
`;
```

Tested on vscode v1.20.1 and vscode-styled-components v0.0.16 under both Linux and Windows.

**Comment by mjbvz** [comment] 2018-03-05 07:38
Duplicate of https://github.com/Microsoft/typescript-styled-plugin/issues/37

**Closed by mjbvz** 2018-03-05 07:38 UTC
