### ISSUE TITLE
Feature Request: Highlight colours

### ISSUE THREAD

**Issue by jameslnewell** [styled-components/vscode-styled-components#11] opened 2017-02-23 12:47 UTC
e.g. [Color Picker for VSCode](https://marketplace.visualstudio.com/items?itemName=anseki.vscode-color) but for CSS in `styled-components`

**Comment by geddski** [comment] 2017-04-11 19:20
yes I miss this from regular CSS files

**Comment by TrevorSayre** [comment] 2017-05-26 15:23
![image](https://cloud.githubusercontent.com/assets/421548/24007461/0a661bb4-0a45-11e7-86f9-4047b3ec86bf.png)

**Comment by ekfuhrmann** [comment] 2018-03-29 15:14
As a temporary work around, [Color Highlight](https://github.com/sergiirocks/vscode-ext-color-highlight) does work within styled components:

![image](https://user-images.githubusercontent.com/8878152/38097025-47a73482-3342-11e8-87e6-3a6bb826cedf.png)

**Comment by jasonwilliams** [comment] 2020-10-05 11:21
duplicate of https://github.com/styled-components/vscode-styled-components/issues/95

**Closed by jasonwilliams** 2020-10-05 11:21 UTC
Labels: enhancement
