### ISSUE TITLE
It breaks all Javascript syntax coloring

### ISSUE THREAD

**Issue by 0x80** [styled-components/vscode-styled-components#19] opened 2017-04-03 14:39 UTC
If I set the file type to CSS (styled components) the CSS gets syntax highlighting, but at the same time everything else looses it.

Any idea why this might happen?

<img width="735" alt="screenshot 2017-04-03 16 34 52" src="https://cloud.githubusercontent.com/assets/1193520/24614842/cce0d184-188c-11e7-9869-908377da3438.png">

**Comment by 0x80** [comment] 2017-04-06 10:51
I using MacOS Sierra btw. 

Also isn't this supposed to work without manually setting the file type to CSS (Styled Components)?

**Comment by julienp** [comment] 2017-04-06 11:34
It's indeed supposed to work without setting the file type to CSS (Styled Components). I've seen it break with certain other plugins installed that overwrite the default javascript grammar. See #16 #8

**Comment by 0x80** [comment] 2017-04-07 08:23
Thanks it was babel-sublime that I was missing!

I didn't have problems with the flow extension.

However the syntax highlighting is not perfect. See the difference here between styled components and (post) css in my editor. For example the px units are not colored the same as the value the belong to.

<img width="644" alt="screenshot 2017-04-07 10 13 21" src="https://cloud.githubusercontent.com/assets/1193520/24791892/2f3ed7da-1b7c-11e7-972b-8f09e3877244.png">
<img width="528" alt="screenshot 2017-04-07 10 13 33" src="https://cloud.githubusercontent.com/assets/1193520/24791895/32b27d9a-1b7c-11e7-9c80-88efb394eb4b.png">

**Comment by 0x80** [comment] 2017-04-08 10:47
I found that installing the sublime-babel extension actually breaks the flow syntax coloring partially. I get the impression that while sublime-babel is fixing certain things that use to be (still?) wrong with vscode syntax grammar, it also works against extensions that assume the native vscode syntax grammar.

So I feel like I'm trying to fix something in one place while breaking something else in another place. Would is be possible for this plugin at some point to use the native vscode syntax grammar? Or does vscode still need to work out some issues? I'm just trying to get a better understanding of the problem here.

This is with sublime-babel installed:

<img width="388" alt="screenshot 2017-04-08 12 32 21" src="https://cloud.githubusercontent.com/assets/1193520/24828247/599d1b12-1c59-11e7-8157-cbf8c9a906ed.png">

And this without:

<img width="488" alt="screenshot 2017-04-08 12 32 52" src="https://cloud.githubusercontent.com/assets/1193520/24828242/52513c44-1c59-11e7-8e06-8b7e41a4013b.png">

**Comment by julienp** [comment] 2017-05-25 09:16
> So I feel like I'm trying to fix something in one place while breaking something else in another place.

Yeah, that's definitely an issue. This extension does *not* replace the standard vscode javascript grammar, rather it injects some additional rules into it. Unfortunately it seems that some plugins that also do this or completely replace the standard grammar can break this.

**Comment by AndreyUtka** [comment] 2018-02-17 22:13
I'm not sure, but I have the same issue:

the original file - https://github.com/AndreyUtka/react-flux-ts-starter-kit/blob/master/build-process/constants.js

<img width="1110" alt="screen shot 2018-02-18 at 12 08 21 am" src="https://user-images.githubusercontent.com/1304912/36346074-eec0e4ce-143f-11e8-9d2d-6d79d6afc8cc.png">

installed plugins: 
- https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
- https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest
- https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense
- https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode
- https://marketplace.visualstudio.com/items?itemName=itryapitsin.Scala
- https://marketplace.visualstudio.com/items?itemName=shinnn.stylelint
- https://marketplace.visualstudio.com/items?itemName=eg2.tslint
- https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components

after disabling vscode-styled-components everything is ok.

**Comment by Cu3PO42** [comment] 2018-02-18 09:25
I can confirm this issue, although it's definitely not related to the ones before. I will try to fix it later though.

**Comment by DiMoNTD** [comment] 2018-03-11 09:39
I have highlight problems with js after styled component.

Example with styled component:

![with_styled](https://i.imgur.com/puizl4j.png)

And example without styled component:

![without_styled](https://i.imgur.com/vZdlUYD.png)

I'm using flow and react-native styled components

**Comment by Cu3PO42** [comment] 2018-03-21 16:35
Unfortunately some unexpected stuff came up in real life and that in conjunction with me getting sick has lead to a delay in dealing with this. Sorry about that. The last issue reported here is the same as reported in #65.

Since there are no other outstanding issues named here, I'm going to close this in favour of #65.

**Closed by Cu3PO42** 2018-03-21 16:35 UTC
