### ISSUE TITLE
No css code prompt

### ISSUE THREAD

**Issue by github-ZH-cn** [styled-components/vscode-styled-components#400] opened 2023-02-26 11:53 UTC
![image](https://user-images.githubusercontent.com/67533362/221408820-665f24ca-ab71-4c1b-b64f-fa3cddf93b3e.png)

**Comment by zhanghairui** [comment] 2023-03-15 22:58
I'm having the same problem

**Comment by jasonwilliams** [comment] 2023-04-01 17:55
duplicate of https://github.com/styled-components/vscode-styled-components/issues/387

**Closed by jasonwilliams** 2023-04-01 17:55 UTC
Labels: bug
